version: '3.8'

services:
  codecept-ui:
    image: api.registry.viomitra.ru/codecept:latest
    deploy:
      placement:
        constraints:
          - node.role == manager  # Запускать контейнер только на нодах manager
      labels:
        - traefik.enable=true
        - traefik.docker.network=traefik-public
        - traefik.constraint-label=traefik-public
        - traefik.http.routers.codecept-http.rule=Host(`autotest.viomitra.ru`)
        - traefik.http.routers.codecept-http.entrypoints=http
        - traefik.http.routers.codecept-http.middlewares=https-redirect
        - traefik.http.routers.codecept-https.rule=Host(`autotest.viomitra.ru`)
        - traefik.http.routers.codecept-https.entrypoints=https
        - traefik.http.routers.codecept-https.tls=true
        - traefik.http.routers.codecept-https.tls.certresolver=le
        - traefik.http.services.codecept.loadbalancer.server.port=3333
    networks:
      - traefik-public

networks:
  traefik-public:
    external: true
